### ISSUE TITLE
Max Force

### ISSUE THREAD

**Issue by 308648** [skaughtx0r/unity-ffb#1]
Hello. Thank you for this library it has helped me a lot! But I was wondering how to know what the max force is? For me it seems to be 10000 but I don't know if this will be true for other wheels as well.

**Comment by skaughtx0r** [comment]
When a device is selected, it will enumerate the axes and put the data into the `axes` property.

Typical usecase, you should be able to just do

```
UnityFFB.instance.axes[0].ffMaxForce
```

**Comment by 308648** [comment]
For my wheel it reports a ffMaxForce of "10". But like I said max force seems to be "10 000". How should I read that?

**Comment by skaughtx0r** [comment]
According to the DirectInput documentation, the actual constant force value range is always -10000 to 10000 ([DICONSTANTFORCE](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee416604(v=vs.85)))

And the [DIDEVICEOBJECTINSTANCE](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee416612(v=vs.85)) which is what is reported in the `axes`. This shows the max force measured in newtons. You could possibly use this to automatically scale the force value.

What I do is just provide strength sliders that set a value from 0 to 1 in my settings to allow the user to adjust forces themselves.

**Comment by 308648** [comment]
Okay I got it now. Thank you for the help!! Awesome!!
